# Generated by Django 5.1.7 on 2026-03-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeltrixApp', '0002_paymentmethod_transaction_reference_id_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='loyalty_status',
            field=models.CharField(default='Bronze', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='loyalty_tier_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='loyalty_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
