# Generated by Django 5.1.7 on 2026-03-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeltrixApp', '0003_user_loyalty_benefits_user_loyalty_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.PositiveIntegerField(unique=True)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_deposit', models.DecimalField(decimal_places=2, default=999999, max_digits=20)),
                ('color', models.CharField(default='#CD7F32', max_length=20)),
                ('icon', models.CharField(default='images/loyalty/bronze.svg', max_length=100)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('referral_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direct_referral_required', models.PositiveIntegerField(default=0)),
                ('referral_deposits_required', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Loyalty Statuses',
                'ordering': ['level'],
            },
        ),
    ]
