# Generated by Django 5.1.7 on 2026-03-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeltrixApp', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='traders'),
        ),
    ]
