# Generated by Django 5.1.7 on 2026-03-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeltrixApp', '0006_trader_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
