# Generated by Django 5.1.7 on 2026-03-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeltrixApp', '0007_user_email_otp_user_email_otp_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('CZK', 'Czech Koruna'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('JPY', 'Japanese Yen')], max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethoddetail',
            name='currency_specific_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VeltrixApp.currency'),
        ),
        migrations.AddField(
            model_name='paymentmethoddetail',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='VeltrixApp.currency'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VeltrixApp.currency'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethoddetail',
            unique_together={('payment_method', 'currency')},
        ),
    ]
