# Generated by Django 5.1.7 on 2026-03-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeltrixApp', '0008_currency_deposit_account_name_deposit_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='cashapp_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethoddetail',
            name='cashapp_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/cashapp/'),
        ),
        migrations.AddField(
            model_name='paymentmethoddetail',
            name='cashapp_tag',
            field=models.CharField(blank=True, help_text='CashApp $Cashtag', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethoddetail',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='PayPal email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethoddetail',
            name='paypal_me_link',
            field=models.URLField(blank=True, help_text='PayPal.Me link', null=True),
        ),
        migrations.AddField(
            model_name='paymentmethoddetail',
            name='paypal_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/paypal/'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('crypto', 'Cryptocurrency'), ('bank', 'Bank Transfer'), ('cashapp', 'CashApp'), ('paypal', 'PayPal')], max_length=20),
        ),
    ]
